In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("HousingData.csv")
print(df)

        CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93   0.0  0.573  6.030   NaN  2.5050    1  273   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  3

In [3]:
df = df.dropna()

In [4]:
x= df.iloc[:,0:13].values
print(x)
y = df.iloc[:,13:14].values
print(y)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [4.5270e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 9.0800e+00]
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]]
[[24. ]
 [21.6]
 [34.7]
 [33.4]
 [28.7]
 [27.1]
 [16.5]
 [15. ]
 [18.9]
 [21.7]
 [20.4]
 [19.9]
 [23.1]
 [17.5]
 [20.2]
 [18.2]
 [13.6]
 [19.6]
 [15.2]
 [14.5]
 [15.6]
 [13.9]
 [16.6]
 [14.8]
 [18.4]
 [21. ]
 [12.7]
 [14.5]
 [13.2]
 [13.1]
 [13.5]
 [21. ]
 [24.7]
 [30.8]
 [34.9]
 [26.6]
 [25.3]
 [21.2]
 [19.3]
 [20. ]
 [14.4]
 [19.4]
 [19.7]
 [25. ]
 [18.9]
 [35.4]
 [24.7]
 [31.6]
 [23.3]
 [19.6]
 [18.7]
 [16. ]
 [22.2]
 [25. ]
 [33. ]
 [23.5]
 [19.4]
 [22. ]
 [17.4]
 [20.9]
 [24.2]
 [21.7]
 [22.8]
 [21.4]
 [20. ]
 [20.8]
 [21.2]
 [28. ]
 [23.9]
 [24

In [5]:
reg = linear_model.LinearRegression()

In [17]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size =0.20,random_state = 42)

In [7]:
reg.fit(x_train,y_train)

LinearRegression()

In [8]:
print(reg.coef_)

[[-1.12187394e-01  4.24404148e-02  2.56728238e-02  1.98383708e+00
  -1.70792571e+01  4.25809072e+00 -2.17413906e-02 -1.42418883e+00
   2.35587949e-01 -1.19971379e-02 -9.75834850e-01  9.59377961e-03
  -3.88619588e-01]]


In [19]:
y_pred = reg.predict(x_test)
print(y_pred)

[[29.22850199]
 [17.5037472 ]
 [21.80803847]
 [30.4942528 ]
 [18.50265527]
 [34.7432311 ]
 [22.07369779]
 [30.7541295 ]
 [33.52029866]
 [14.82910783]
 [22.14507214]
 [41.26427356]
 [22.51242483]
 [16.87300668]
 [19.0023074 ]
 [20.77110711]
 [17.26921288]
 [15.48568273]
 [22.69482862]
 [14.12652975]
 [18.19319969]
 [20.48292217]
 [17.04235173]
 [29.66737037]
 [26.09718411]
 [16.06132841]
 [27.09746911]
 [31.45656662]
 [22.64238912]
 [27.06681913]
 [41.10181897]
 [18.21320236]
 [23.062681  ]
 [17.41202659]
 [17.39546606]
 [21.076803  ]
 [22.38598488]
 [21.66963934]
 [22.9118984 ]
 [20.80249561]
 [27.70046219]
 [34.60121409]
 [22.25931447]
 [30.83868791]
 [35.33229137]
 [19.76393425]
 [24.99195034]
 [10.39133132]
 [19.75538217]
 [25.31114768]
 [21.55934818]
 [25.89776968]
 [14.23212614]
 [18.66822307]
 [18.34126683]
 [24.31756905]
 [43.40891373]
 [22.87668508]
 [15.3452895 ]
 [23.17268086]
 [21.11796307]
 [21.4821572 ]
 [14.66508216]
 [28.92300146]
 [-3.71655126]
 [32.60224615]
 [16.81628